---
- name: set admin password
  paloaltonetworks.panos.panos_admpwd:
    ip_address: "192.168.251.54"
    username: "admin"
    key_filename: "~/.ssh/id_rsa.pub"
    newpassword: "Qwe123456#"
  register: result
  retries: 10
  delay: 30