---
- name: Set login banner message
  delegate_to: localhost
  paloaltonetworks.panos.panos_mgtconfig:
    provider: "{{ provider }}"
    login_banner: "#### AUTHORIZED ACCESS ONLY!! ####"

- name: Commit the change
  delegate_to: localhost
  paloaltonetworks.panos.panos_commit_firewall:
    provider: "{{ provider }}"
    description: Change login banner message