---
- name: Set dns servers
  delegate_to: localhost
  paloaltonetworks.panos.panos_mgtconfig:
    provider: "{{ provider }}"
    dns_server_primary: "{{ primary_dns }}"
    dns_server_secondary: "{{ secondary_dns | default(omit) }}"

- name: Commit the change
  delegate_to: localhost
  paloaltonetworks.panos.panos_commit_firewall:
    provider: "{{ provider }}"
    description: Change DNS