---
- name: Set dns servers
  paloaltonetworks.panos.panos_mgtconfig:
    provider: "{{ provider }}"
    dns_server_primary: "{{ primary_dns }}"
    dns_server_secondary: "{{ secondary_dns | default(omit) }}"