---
- name: Configure new ip for interface mgmt
  delegate_to: localhost
  paloaltonetworks.panos.panos_interface:
    provider: "{{ provider }}"
    if_name: "Management"
    ip: "{{ management_ip }}"
    mode: layer3
    enable_dhcp: false
    state: merged

#- name: Commit the change
#  delegate_to: localhost
#  paloaltonetworks.panos.panos_commit_firewall:
#    provider: "{{ provider }}"
#    description: Change management ip interface