---
- name: Configure new ip for interface mgmt
  delegate_to: localhost
  paloaltonetworks.panos.panos_type_cmd:
    provider: "{{ provider }}"
    cmd: "set deviceconfig system ip-address {{ management_ip }} netmask {{ subnet_mask }}"
    
#- name: Commit the change
#  delegate_to: localhost
#  paloaltonetworks.panos.panos_commit_firewall:
#    provider: "{{ provider }}"
#    description: Change management ip interface