---
- name: Configure new ip for interface mgmt
  delegate_to: localhost
  paloaltonetworks.panos.panos_type_cmd:
    provider: "{{ provider }}"
    xpath: /config/devices/entry[@name='localhost.localdomain']/deviceconfig/system/ip-address

#- name: Commit the change
#  delegate_to: localhost
#  paloaltonetworks.panos.panos_commit_firewall:
#    provider: "{{ provider }}"
#    description: Change management ip interface