---
- hosts: 192.168.251.54
  gather_facts: false
  tasks:
    
    - name: install collections
      delegate_to: localhost
      ansible.builtin.shell: ansible-galaxy collection install -r ../collections/requirements.yml

    - name: Debug
      ansible.builtin.debug:
        var: ansible_facts

    - name: Import role gather information
      ansible.builtin.import_role:
        name: ../roles/gather_info